# Generated by Django 4.0.2 on 2022-04-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleComment',
        ),
        migrations.DeleteModel(
            name='SamplePost',
        ),
    ]
