# Generated by Django 4.0.4 on 2022-05-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='account_name',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='env',
            name='account_pw',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
