# Generated by Django 4.0.2 on 2022-04-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='general', max_length=20),
        ),
    ]
