# Generated by Django 4.0.4 on 2022-05-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_env_account_name_env_account_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
