# Generated by Django 4.0.2 on 2022-04-10 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_delete_samplecomment_delete_samplepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbelongclass',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_id', to='app_main.class'),
        ),
    ]
