# Generated by Django 4.0.4 on 2022-06-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_user_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBelongAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('result', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app_main.user')),
            ],
            options={
                'db_table': 'ssql_user_belong_auth',
            },
        ),
    ]
