# Generated by Django 4.0.4 on 2022-06-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_userbelongauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemgroup',
            name='activate',
            field=models.BooleanField(default=1),
        ),
    ]
