version: "3.9"
services:

  nginx-proxy:
    image: "iml1111/imnginx:latest"
    container_name: "nginx-proxy"
    restart: "unless-stopped"
    ports:
      - "5001:80" # check
    depends_on:
      - "ssql-server"
    environment:
      - SERVER_ADDR=ssql-server:5000
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/nginx-health-check || exit 1"]
      interval: 600s
      timeout: 10s
      retries: 1
      start_period: 15s
  
  ssql-server:
    image: "sejongsql:latest" # check
    container_name: "ssql-server"
    restart: "unless-stopped"
    ports:
      - "5002:5000" # check
    volumes:
      - "/home/your/log:/home/log" # check
      - "/home/your/assets:/home/assets" # check
    depends_on:
      - "ssql-mysql"
    env_file:
      - "ssql.env" # check
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail 127.0.0.1:5000 || exit 1"]
      interval: 600s
      timeout: 10s
      retries: 1
      start_period: 15s
  
  ssql-mysql:
    image: mysql:8.0.28 # check
    container_name: ssql-mysql
    volumes:
      - /home/data/mysql:/var/lib/mysql # check
    ports:
      - 3307:3306 # check
    env_file:
      - "ssql.env" # check