version: "3.9"
services:

  nginx-proxy:
    image: "iml1111/imnginx:latest"
    container_name: "nginx-proxy"
    restart: "unless-stopped"
    ports:
      - "5001:80"
    depends_on:
      - "ssql-server"
    environment:
      - SERVER_ADDR=ssql-server:5000
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/nginx-health-check || exit 1"]
      interval: 600s
      timeout: 10s
      retries: 1
      start_period: 15s
  
  ssql-server:
    image: "SSQL-IMAGE:latest" # check
    container_name: "ssql-server"
    restart: "unless-stopped"
    ports:
      - "5002:5000"
    volumes:
      - "/home/ubuntu/log:/home/log"
      - "/home/ubuntu/assets:/home/assets"
    depends_on:
      - "mongodb"
    env_file:
      - "ssql.env"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail 127.0.0.1:5000 || exit 1"]
      interval: 600s
      timeout: 10s
      retries: 1
      start_period: 15s
  
  ssql-mysql:
    image: mysql:8.0.28
    container_name: ssql-mysql
    volumes:
      - /your/data/path/mysql:/var/lib/mysql # check
    ports:
      - 3307:3306
    environment:
      - "ssql.env"